default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: 
  timeout: 5000

development:
  <<: *default
  database: housecoffee_development
  host: db

test:
  <<: *default
  database: housecoffee_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
