default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  timeout: 5000

development:
  <<: *default
  database: housecoffee_development
  host: db

test:
  <<: *default
  database: housecoffee_test
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
